### ISSUE TITLE
How to change "root" for hosting on github?

### ISSUE THREAD

**Issue by philippefaes** [jandecaluwe/urubu-quickstart#3]
All internal links start with "/", so that they are at the root of the server. This works fine when visiting the website: http://urubu-quickstart.jandecaluwe.com. The start page is at http://urubu-quickstart.jandecaluwe.com/start.html

However, if you visit the same site at the GitHub provide location, the links are broken. Now the start page links to http://jandecaluwe.github.io/start.html, but it should be http://jandecaluwe.github.io/urubu-quickstart/start.html. 

If we want to deploy our own documentation through GitHub (without a custom URL), is there a way to fix the links?

**Comment by jandecaluwe** [comment]
Check the `baseurl` option: http://urubu.jandecaluwe.com/manual/structure.html#special-files

Also relevant: http://urubu.jandecaluwe.com/faq/baseurl-preview.html
